global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "crud"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "crud"
    static_configs:
      - targets: ["crud:8001"]